file=open('data.txt','w',encoding="utf-8")
text=input("Введите текст:")
file.write(text)
file.close()
file1=open('data1.txt','w',encoding="utf-8")
text1=input("Введите текст:")
file1.write(text1)
file1.close()